[package]
name = "light-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version="0.7.0", default_features = false }
bevy_pixels = "0.5.0"
vulkano-shaders = "0.29.0"
vulkano = "0.29.0"
nalgebra = "*"
nalgebra-glm = "0.17.0"
rand = "0.8.5"
